# Generated by Django 3.0.5 on 2020-06-02 15:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('phoneno', models.IntegerField(max_length=15)),
                ('emailid', models.EmailField(max_length=80)),
                ('address', models.TextField(max_length=250)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2020, 6, 2, 15, 17, 46, 59250, tzinfo=utc))),
            ],
        ),
    ]
